Add Volume Controller
89netraM/hotheaded-vscode pull request #13
Opened 2023-06-06 22:12 UTC by DiegoxK

This pull request addresses issue #4 by adding a volume control feature to the extension. Users can now adjust the volume of the voice lines played by the extension.

2023-06-08 13:56 UTC, 89netraM commented
First off, thank you for these PRs! This comment addresses both #13 and #14.

The code updates seem fine at first glance, however before taking a closer look I would like to ask you to fix the formating. Notice that a lot of extra lines has been changed (see the [diff](https://github.com/89netraM/hotheaded-vscode/pull/13/files)) due to whitespace changes.  
I would also like you to change the defaults to align with the current behaviour, set default volume to 1.0, and default delay to exactly 0 ms.

2023-06-14 14:02 UTC, DiegoxK commented
Got it, i forgot to deactivate the default usage of prettier and i that formatted all the file sorry.
Let me work on it

2023-06-14 15:06 UTC, DiegoxK commented
Okay, I believe this branch now only includes the necessary changes made to `Player.ts` and `package.json`, along with a default volume of 1.

2023-06-14 15:44 UTC, 89netraM requested changes
Have you tested these changes?

Can you also commit the `package-lock.json` file. This will help when building in the future.

2023-06-14 15:44 UTC, 89netraM commented on src/Player.ts
> +  fs.createReadStream(file).pipe(v);
Line 18 has one tab as indentation, as the rest of the file, but 19-25 has two spaces.

2023-06-14 15:44 UTC, 89netraM commented on src/Player.ts
> +import Volume = require("pcm-volume");
Is this the correct syntax here?

2023-06-14 15:52 UTC, DiegoxK commented on src/Player.ts
> +import Volume = require("pcm-volume");
I don't really know why a regular import doesn't work with pcm-volume but this is the only way i manage to make it work

2023-06-14 16:03 UTC, 89netraM commented on src/Player.ts
> +import Volume = require("pcm-volume");
[The docs](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require) suggest it has something to do with how the exports are done, but (`pcm-volume`)[https://github.com/reneraab/pcm-volume/blob/2aaaf05c2e1b69e7419af42ed45e1b6a4b191cce/index.js#L44] seem to do a regular `module.exports`. Weird 👍

2023-06-14 16:06 UTC, DiegoxK commented
I have tested the changes, and setting both the maximum and minimum values to 0 produces the default behavior where the voices can be heard for each error

2023-06-14 16:15 UTC, DiegoxK commented on src/Player.ts
> +import Volume = require("pcm-volume");
Good to know, thanks!

2023-06-14 16:17 UTC, 89netraM approved these changes
Great! Because I can't get it to install on my PC right now (some npm issue), but I'll trust you that it works 👍

Great work! Thank you!

2023-06-14 16:19 UTC, merged